apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.7.0
    replicas: 1 # you can increase it for more broker replica 
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: minikube
        port: 9094
        type: internal
        tls: false
        configuration:
          brokers:
            - broker: 0
              advertisedHost: 127.0.0.1
              advertisedPort: 19094
            - broker: 1
              advertisedHost: 127.0.0.1
              advertisedPort: 19095
            - broker: 2
              advertisedHost: 127.0.0.1
              advertisedPort: 19096
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.7"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: 3 # you can increase it for more ZK replica
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-cluster-kafka-0
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: my-cluster-kafka-0
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-kafka
    strimzi.io/pool-name: kafka
  ports:
    - protocol: TCP
      port: 19094
      targetPort: 9094
---
apiVersion: v1
kind: Service
metadata:
  name: my-cluster-kafka-1
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: my-cluster-kafka-1
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-kafka
    strimzi.io/pool-name: kafka
  ports:
    - protocol: TCP
      port: 19095
      targetPort: 9094
---
apiVersion: v1
kind: Service
metadata:
  name: my-cluster-kafka-2
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: my-cluster-kafka-2
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-kafka
    strimzi.io/pool-name: kafka
  ports:
    - protocol: TCP
      port: 19096
      targetPort: 9094
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
