grpc:
  network: tcp
  host: localhost
  port: 50051

postgres:
  driver_name: postgres
  user: postgres
  db_name: practice
  ssl_mode: disable
  password: umagos
  host: localhost

kafka:
  brokers: localhost:9092 
  consumer_group: test-consumer-group
  topics: test-topic
  assignor: roundrobin
  oldest: true

rest:
  read_timeout: 60
  write_timeout: 60
  server_url: localhost:3000
