grpc:
  network: tcp
  host: localhost
  port: 50051

database:
  driver_name: postgres
  user: postgres
  db_name: practice
  ssl_mode: disable
  password: umagos
  host: localhost

kafka:
  brokers: localhost:9092 
  consumer_group: test-consumer-group
  topics: test-topic
  assignor: roundrobin
  oldest: true
